<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Author>gaypotatoemma</Author>
    <Name>Quest Banners</Name>
    <RepoUrl>https://github.com/GayPotatoEmma/botw-quest-banner</RepoUrl>
    <InternalName>QuestBanners</InternalName>
    <AssemblyVersion>0.0.0.1</AssemblyVersion>
    <Punchline>Custom Quest Banners</Punchline>
    <Description>Adds several styles of Quest Banners to replace the Vanilla Styles, inspired by various other games.</Description>
    <Tags>botw, totk, zelda, ui, quest,</Tags>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="assets\fonts\HyliaSerifBeta-Regular.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
    <Content Include="assets\audio\questbanner.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
    <Content Include="assets\audio\questcomplete.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>
</Project>
